language: python

# sudo false implies containerized builds
sudo: false

addons:
  apt:
    packages:
    - ffmpeg


notifications:
    email: false

python:
  - 2.7
  - 3.4
  - 3.5

cache:
    directories:
    - $HOME/miniconda

env:
  global:
    # Directory where tests are run from
    - CONDA_DEPS="pip nose numpy scipy scikit-learn"
    - ENV_NAME="test-environment"

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
# Install conda only if necessary
- command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
   bash miniconda.sh -b -f -p $MINICONDA; }
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
- conda update --all
- hash -r
- source activate $ENV_NAME

install:
    - pip install python-coveralls pytest-faulthandler
    - pip install -e .[docs,tests]

script:
    - py.test

after_success:
    - coveralls
