language: python

# sudo false implies containerized builds
sudo: false

notifications:
    email: false

python:
  - 2.7
  - 3.4
  - 3.5

cache:
    directories:
    - $HOME/env

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

install:
    - pip install -e .[docs,tests]

script:
    - py.test

after_success:
    - coveralls
